-- ============================================================================
-- migration: create enum types
-- description: creates custom enum types for flashcard application
-- affected: type definitions
-- ============================================================================

-- create enum type for flashcard source tracking
-- this enum allows us to distinguish between ai-generated content (unedited),
-- ai-generated content that was edited by user, and manually created flashcards
create type flashcard_source_type as enum (
    'ai-full',      -- flashcard generated by ai and accepted without modifications
    'ai-edited',    -- flashcard generated by ai but edited by user before accepting
    'manual'        -- flashcard created manually by user without ai assistance
);

-- add comment to document the enum type
comment on type flashcard_source_type is 'defines the origin of flashcard content for analytics and user transparency';

