-- ============================================================================
-- migration: create generations table
-- description: creates table to store ai generation session metadata and statistics
-- affected tables: generations (new)
-- special considerations:
--   - includes unique constraint on (user_id, source_text_hash) to prevent duplicate processing
--   - tracks detailed statistics for ai acceptance rate analysis
--   - includes cascade delete to ensure gdpr compliance
-- ============================================================================

-- create generations table to track ai flashcard generation sessions
create table generations (
    -- primary key: unique identifier for each generation session
    id uuid primary key default gen_random_uuid(),
    
    -- foreign key: owner of the generation session
    -- on delete cascade ensures user data is completely removed when account is deleted (gdpr compliance)
    user_id uuid not null references auth.users(id) on delete cascade,
    
    -- sha-256 hash of source text (64 characters hex)
    -- used to prevent duplicate processing of the same content
    source_text_hash char(64) not null,
    
    -- length validation ensures text is within acceptable range for llm processing
    source_text_length integer not null,
    constraint check_source_text_length check (source_text_length between 1000 and 10000),
    
    -- llm model identifier for tracking which model generated the flashcards
    model_name varchar not null,
    
    -- statistics counters for measuring ai effectiveness
    count_generated integer not null default 0,          -- total flashcards generated by ai
    count_accepted_unedited integer not null default 0,  -- flashcards accepted without changes
    count_accepted_edited integer not null default 0,    -- flashcards accepted after user edits
    
    -- audit timestamps
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- add comments for documentation
comment on table generations is 'stores metadata and statistics for ai flashcard generation sessions';
comment on column generations.source_text_hash is 'sha-256 hash of input text to prevent duplicate processing';
comment on column generations.count_generated is 'total number of flashcard proposals generated by ai';
comment on column generations.count_accepted_unedited is 'number of ai-generated flashcards accepted without modifications';
comment on column generations.count_accepted_edited is 'number of ai-generated flashcards accepted after user edits';

-- create trigger to automatically update updated_at timestamp
create trigger update_generations_modtime
    before update on generations
    for each row
    execute function update_updated_at_column();

-- ============================================================================
-- row level security (rls) configuration
-- ============================================================================

-- enable rls to ensure users can only access their own generation sessions
alter table generations enable row level security;

-- policy: allow authenticated users to select their own generation records
create policy "authenticated users can select own generations"
    on generations
    for select
    to authenticated
    using (auth.uid() = user_id);

-- policy: allow authenticated users to insert their own generation records
create policy "authenticated users can insert own generations"
    on generations
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- policy: allow authenticated users to update their own generation records
-- this is needed to update statistics counters when flashcards are accepted
create policy "authenticated users can update own generations"
    on generations
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- policy: allow authenticated users to delete their own generation records
create policy "authenticated users can delete own generations"
    on generations
    for delete
    to authenticated
    using (auth.uid() = user_id);

